# Generated by Django 4.1.7 on 2023-04-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_game_delete_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("prompt", models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.CreateModel(
            name="ImageSets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.game"
                    ),
                ),
                ("image", models.ManyToManyField(to="api.image")),
            ],
        ),
    ]
