# Generated by Django 4.1.7 on 2023-04-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_player_round_session_vote_round_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="nick",
            field=models.CharField(default="UNKNOWN", max_length=50),
        ),
    ]
