# Generated by Django 4.1.7 on 2023-04-01 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_image_alter_game_image_imagesets"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImageSets",
            new_name="ImageSet",
        ),
    ]
