# Generated by Django 4.1.7 on 2023-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_imagesets_imageset"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageset",
            name="name",
            field=models.CharField(default="Image Set", max_length=100),
        ),
    ]
