version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - 3001:80
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    depends_on:
      - redis

  redis:
    image: "redis:latest"