version: '3.7'

services:
  frontend:
    image: mateuszn65/aigame:frontend
    ports:
      - 3001:80
    volumes:
      - ./frontend:/app

  backend:
    image: mateuszn65/aigame:backend
    depends_on:
      - redis

  redis:
    image: "redis:latest"